apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: influxdb
  name: influxdb
spec: 
  ports: 
    - port: 8086
  selector: 
    app: influxdb
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/influxdb
  persistentVolumeReclaimPolicy: Retain
  # claimRef:
  #   name: influxdb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: influxdb-pv
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: influxdb
  name: influxdb
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: influxdb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: influxdb
    spec: 
      containers: 
        - image: my_influxdb
          name: influxdb
          imagePullPolicy: Never
          env:
          - name: INFLUXDB_META_DIR
            value: /var/lib/influxdb/meta
          - name: INFLUXDB_DATA_DIR
            value: /var/lib/influxdb/data
          - name: INFLUXDB_DATA_WAL_DIR
            value: /var/lib/influxdb/wal
          ports:
            - name: influxdb
              containerPort: 8086
          volumeMounts:
            - name: influxdb-persistent-storage
              mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-persistent-storage
          persistentVolumeClaim:
            claimName: influxdb-pvc
