apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
    - name: wordpress
      port: 5050
      protocol: TCP
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name : wordpress
          image: my_wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050