apiVersion: 1
datasources:
  - name: Influxdb
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    database: telegraf
    basicAuth: true
    basicAuthUser: ekim
    basicAuthPassword: password
    # user: telegraf
    # password: telegraf
    editable: false